--- src2/Makefile	2016-02-03 18:14:44.000000000 +0100
+++ src/Makefile	2017-02-22 15:21:23.620664965 +0100
@@ -1,15 +1,15 @@
-# MKMF template makefile for protected mode executables.
-FC        = gfortran
-LINKER    = gfortran
-PROGRAM         = x13asv11b39
-DEST      = .
-EXTHDRS         =
-FFLAGS    = -O0
-HDRS            =
-LDFLAGS   = -s
+FC        ?= gfortran
+LINKER    ?= gfortran
+PROGRAM   ?= x13
+DEST      ?= .
+EXTHDRS   =
+FFLAGS    ?= -O0
+HDRS      =
+LDFLAGS   ?= -s
 LDMAP     = 
 LIBS      =
 MAKEFILE  = Makefile
+
 OBJS            = aaamain.o abend.o acf.o acfar.o acfdgn.o \
                   acfhdr.o addadj.o addaic.o addate.o addeas.o \
                   addfix.o addlom.o addmat.o addmul.o addotl.o \
@@ -287,14 +287,16 @@
                   compcrodiag.f phasegain.f altundovrtst.f \
                   getrevdec.f
 
-$(PROGRAM):     $(OBJS) $(LIBS)
+$(PROGRAM): $(OBJS) $(LIBS)
 	$(LINKER) -static -o $@ $(OBJS) $(LDMAP) $(LIBS) $(LDFLAGS)
 
-clean:;         @rm -f $(OBJS)
+clean:
+	@rm -f $(OBJS)
 
-install:   $(PROGRAM)
+install: $(PROGRAM)
 	@echo Installing $(PROGRAM) in $(DEST)
 	@if not $(DEST)x==.x copy $(PROGRAM) $(DEST)
+
 ### OPUS MKMF:  Do not remove this line!  Automatic dependencies follow.
 
 aaamain.o:  build.prm cchars.i chrt.cmn error.cmn hiddn.cmn lex.i \
